language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config flex bison xsltproc docbook-xsl libevtlog-dev libnet1-dev libglib2.0-dev libdbi0-dev libssl-dev libjson0-dev libwrap0-dev libpcre3-dev libcap-dev libesmtp-dev libgeoip-dev
before_script:
  - ./autogen.sh
script:
  - ./configure --with-ivykis=internal --prefix=$HOME/install/syslog-ng --enable-pacct
  - make
  - make check
compiler:
  - gcc
  - clang
branches:
  only:
    - master
    - /^upstream\/mirror\/.*/
    - /^sandbox\/.*/
    - /^merge-queue\/.*/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
