language: c
install: sudo apt-get update && sudo apt-get install pkg-config flex bison xsltproc docbook-xsl libevtlog-dev libnet1-dev libglib2.0-dev libdbi0-dev libssl-dev libjson0-dev libwrap0-dev libpcre3-dev libcap-dev
before_script:
  - ./autogen.sh
script:
  - ./configure --with-ivykis=internal --prefix=$HOME/install/syslog-ng
  - make
  - make install
  - make check
compiler:
  - gcc
  - clang
branches:
  only:
    - master
    - /^upstream\/mirror\/.*/
    - /^sandbox\/.*/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
    template:
      - "%{author} - %{repository}#%{branch} @ %{commit}: %{message} (%{build_url})"
